#!/usr/bin/env python3
"""Generate the Inno language sections from GameHQ's canonical locale registry."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
REQUIRED_FIELDS = (
    "inno_language",
    "inno_message_file",
    "inno_language_name",
    "inno_language_id",
    "inno_app_locale",
    "inno_order",
    "inno_source_kind",
    "inno_source_locale",
    "inno_fallback_locale",
)


def production_locales(manifest: dict) -> list[dict]:
    locales = [
        locale
        for locale in manifest["locales"]
        if locale.get("state") == "enabled" and locale.get("tier") == 1
    ]
    for locale in locales:
        missing = [field for field in REQUIRED_FIELDS if field not in locale]
        if missing:
            raise ValueError(f"{locale.get('tag', '<unknown>')} lacks {', '.join(missing)}")
        if locale["inno_app_locale"] != locale["tag"]:
            raise ValueError(f"{locale['tag']} changes the application's semantic locale")

    for field in ("inno_language", "inno_language_id", "inno_order"):
        values = [locale[field] for locale in locales]
        if len(values) != len(set(values)):
            raise ValueError(f"duplicate installer {field}")
    return sorted(locales, key=lambda locale: locale["inno_order"])


def render(manifest: dict) -> str:
    locales = production_locales(manifest)
    lines = [
        "; Generated by tools/i18n/generate_inno_languages.py.",
        "; Source of truth: i18n/locales.json. Do not edit this file directly.",
        "",
        "[Languages]",
    ]
    for locale in locales:
        aliases = ",".join(locale.get("aliases", [])) or "none"
        fallback = locale["inno_fallback_locale"] or "none"
        lines.append(
            f"; locale={locale['tag']}; app={locale['inno_app_locale']}; "
            f"aliases={aliases}; source={locale['inno_source_kind']}:"
            f"{locale['inno_source_locale']}; fallback={fallback}"
        )
        lines.append(
            f'Name: "{locale["inno_language"]}"; '
            f'MessagesFile: "{locale["inno_message_file"]}"'
        )

    lines.extend(("", "[LangOptions]"))
    for locale in locales:
        prefix = locale["inno_language"]
        lines.append(f"{prefix}.LanguageName={locale['inno_language_name']}")
        lines.append(f"{prefix}.LanguageID={locale['inno_language_id']}")
    return "\n".join(lines) + "\n"


def render_bootstrap(manifest: dict) -> str:
    locales = production_locales(manifest)
    lines = [
        "{ Generated by tools/i18n/generate_inno_languages.py. }",
        "{ Source of truth: i18n/locales.json. Do not edit this file directly. }",
        "",
        "function CanonicalLocaleForInstallerLanguage(const Language: String): String;",
        "begin",
        "  Result := '';",
    ]
    for index, locale in enumerate(locales):
        keyword = "if" if index == 0 else "else if"
        lines.extend(
            (
                f"  {keyword} CompareText(Language, '{locale['inno_language']}') = 0 then",
                f"    Result := '{locale['inno_app_locale']}'",
            )
        )
    lines.extend(("end;", ""))
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", type=Path, default=ROOT / "i18n" / "locales.json")
    parser.add_argument(
        "--output",
        type=Path,
        default=ROOT / "packaging" / "generated" / "InnoLanguages.iss",
    )
    parser.add_argument(
        "--bootstrap-output",
        type=Path,
        default=ROOT / "packaging" / "generated" / "InnoLanguageBootstrap.iss",
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    manifest = json.loads(args.manifest.read_text(encoding="utf-8"))
    expected = render(manifest)
    expected_bootstrap = render_bootstrap(manifest)
    if args.check:
        actual = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        if actual != expected:
            print(f"stale generated Inno language mapping: {args.output}")
            return 1
        actual_bootstrap = (
            args.bootstrap_output.read_text(encoding="utf-8")
            if args.bootstrap_output.exists()
            else ""
        )
        if actual_bootstrap != expected_bootstrap:
            print(f"stale generated Inno language bootstrap: {args.bootstrap_output}")
            return 1
        print(
            "Inno language mapping and bootstrap are current "
            f"({len(production_locales(manifest))} locales)"
        )
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(expected, encoding="utf-8", newline="\n")
    args.bootstrap_output.parent.mkdir(parents=True, exist_ok=True)
    args.bootstrap_output.write_text(expected_bootstrap, encoding="utf-8", newline="\n")
    print(
        f"generated {args.output} and {args.bootstrap_output} "
        f"({len(production_locales(manifest))} locales)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
