#!/usr/bin/env python3
"""Generate GameHQ-owned Inno CustomMessages from the canonical message registry."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]


def production_locales(locale_manifest: dict) -> list[dict]:
    return sorted(
        (
            locale
            for locale in locale_manifest["locales"]
            if locale.get("state") == "enabled" and locale.get("tier") == 1
        ),
        key=lambda locale: locale["inno_order"],
    )


def render(locale_manifest: dict, message_manifest: dict) -> str:
    locales = production_locales(locale_manifest)
    messages = message_manifest["messages"]
    translations = message_manifest["translations"]
    source_locale = message_manifest["source_locale"]
    lines = [
        "; Generated by tools/i18n/generate_inno_custom_messages.py.",
        "; Source of truth: packaging/i18n/custom-messages.json. Do not edit directly.",
        "; Unqualified en-US values are the complete fallback for every installer language.",
        "",
        "[CustomMessages]",
        "; locale=en-US; fallback=none",
    ]
    for message in messages:
        lines.append(f"{message['key']}={translations[source_locale][message['key']]}")

    for locale in locales:
        tag = locale["tag"]
        if tag == source_locale:
            continue
        lines.extend(("", f"; locale={tag}; fallback={message_manifest['fallback_locale']}"))
        prefix = locale["inno_language"]
        for message in messages:
            lines.append(f"{prefix}.{message['key']}={translations[tag][message['key']]}")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--locales", type=Path, default=ROOT / "i18n" / "locales.json")
    parser.add_argument(
        "--messages",
        type=Path,
        default=ROOT / "packaging" / "i18n" / "custom-messages.json",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=ROOT / "packaging" / "generated" / "InnoCustomMessages.iss",
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    locale_manifest = json.loads(args.locales.read_text(encoding="utf-8"))
    message_manifest = json.loads(args.messages.read_text(encoding="utf-8"))
    expected = render(locale_manifest, message_manifest)
    if args.check:
        actual = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        if actual != expected:
            print(f"stale generated Inno CustomMessages: {args.output}")
            return 1
        print(
            f"Inno CustomMessages are current "
            f"({len(message_manifest['messages'])} messages, "
            f"{len(production_locales(locale_manifest))} locales)"
        )
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(expected, encoding="utf-8", newline="\n")
    print(
        f"generated {args.output} "
        f"({len(message_manifest['messages'])} messages, "
        f"{len(production_locales(locale_manifest))} locales)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
