#pragma once
#include <QHash>
#include <QObject>
#include <QSqlDatabase>
#include <QString>
#include <QStringList>
#include <QVector>

// SQLite metadata store (gamehq.db). Schema versioned via PRAGMA user_version;
// see docs/database.md. Hard rule: favorites are never auto-deleted.

struct CaptureRecord
{
    int id = -1;
    QString filePath;
    QString type;          // "screenshot" | "video"
    int gameId = -1;
    QString gameName;
    QString createdAt;     // ISO 8601
    bool isFavorite = false;
    QString thumbnailPath;
    QString source;
};

// One captures row as seen by a bulk scan: enough to answer "is this file
// already registered, and does it still need a thumbnail?" without a query per file.
struct CaptureIndexEntry
{
    QString thumbnailPath;   // empty when unset or when the row is tombstoned
    bool deleted = false;    // deleted_at IS NOT NULL
};

struct GameEntry
{
    int id = -1;
    QString name;
    QString iconPath;
    QString executablePath;
};

struct BindingRow
{
    QString deviceType;    // "keyboard" | "controller"
    QString inputCode;     // "Share", "Ctrl+Shift+S", …
    QString action;        // "screenshot", "save_replay", "overlay_toggle", …
    QString pressType;     // "tap" | "hold" | "combo"
    int holdMs = 0;        // 0 = not applicable
};

// A user override for one action/slot. Built-in defaults live in ActionCatalog
// (and, until the resolver lands, HotkeyManager); this table only ever holds
// explicit changes, so an empty table means "every action uses its default".
struct BindingOverrideRow
{
    QString deviceGroup;    // "keyboard" | "controller"
    QString deviceProfile;  // device family/fingerprint scope; empty = applies to all devices in the group
    QString actionId;       // ActionCatalog id, e.g. "global.screenshot"
    int slot = 1;           // 1 = primary, 2 = secondary
    QString triggerCode;    // canonical control id or key chord; empty when unbound
    QString activation = QStringLiteral("press"); // "press" | "tap" | "hold" (v4 canonical)
    int holdMs = 0;         // 0 = not applicable, or "use the configured default" for a hold
    bool unbound = false;   // explicit "no trigger" override
    // Appended last so every existing brace-initialization keeps its meaning.
    int tapCount = 1;       // taps a "tap" activation needs, 1-3
};

// Named mapping preset (schema v8, docs/mapping-presets.md). Identity is the
// opaque id, never the name: renaming keeps every assignment working. Content
// is a sparse set of rows in the binding shape above, scoped to one device
// group. Storage only — choosing a winner is the input layer's job (cpo-p04).
struct MappingPreset
{
    QString id;             // opaque, immutable; generated by storage
    QString deviceGroup;    // "keyboard" | "controller" | "mouse"
    QString name;           // display name, unique per group (trimmed, case-insensitive)
    QString origin;         // "user" | "migration"
    QString createdAt;      // ISO 8601 (UTC)
    QString updatedAt;      // ISO 8601 (UTC)
};

struct MappingPresetRow
{
    QString actionId;       // ActionCatalog id, e.g. "global.screenshot"
    int slot = 1;           // 1 = primary, 2 = secondary
    QString triggerCode;    // canonical control id or key chord; empty when unbound
    QString activation = QStringLiteral("press"); // "press" | "tap" | "hold" | "double_tap"
    int holdMs = 0;         // 0 = not applicable, or "use the configured default" for a hold
    bool unbound = false;   // explicit "no trigger"
    int tapCount = 1;       // taps a "tap" activation needs, 1-3
};

// One typed assignment target -> preset. The kind is stored with the row and is
// never inferred from the key text: `controller` follows a durable pad
// identity, `legacy_slot` follows a slot fingerprint, `game` matches a game's
// executable key (a games row id is auxiliary cache only), `group_default` is
// the group fallback (empty key; no row means built-in defaults).
struct MappingAssignment
{
    int id = -1;
    QString deviceGroup;
    QString presetId;
    QString targetKind;   // "controller" | "legacy_slot" | "game" | "group_default"
    QString targetKey;    // controller/legacy_slot/game key; empty for group_default
    int gameRowId = -1;   // UI join cache for `game` targets; never a match key
};

// A historical device-profile key whose converted preset is not an active
// assignment. A stored `controller-…` key cannot be classified offline (strong
// and weak ids have the same shape), so it waits here for runtime proof and is
// promoted by cpo-p03, never by syntax (docs/mapping-presets.md section 6).
struct MappingPresetSource
{
    QString deviceGroup;
    QString sourceKey;          // historical device_profile key, e.g. "controller-<hex>"
    QString convertedPresetId;  // converted content; empty when nothing was converted
    QString status;             // "unverified" | "promoted" | "retired"
    QString createdAt;          // ISO 8601 (UTC)
    QString promotedAt;         // written only by promoteMappingPresetSource()
    QString note;
};

struct ControllerLayoutRow
{
    QString logicalId;
    QString layoutSignature;
    QStringList buttonLabels;
    bool needsReconfirmation = false;
};

class CaptureDatabase : public QObject
{
    Q_OBJECT
public:
    explicit CaptureDatabase(QString filePath, QObject* parent = nullptr);
    ~CaptureDatabase() override;

    // Highest schema this build understands. A database stamped higher was
    // written by a newer GameHQ and must never be modified by this one.
    static constexpr int kCurrentSchemaVersion = 9;

    bool open();      // opens + runs pending migrations
    int schemaVersion() const;

    // Captures. category: all | recent | favorites | screenshots | clips.
    // gameId >= 0 filters to one game. Returns newest first.
    QVector<CaptureRecord> listCaptures(const QString& category, int gameId = -1) const;
    bool hasCapture(const QString& filePath) const;
    // Whole-table snapshot keyed by stored path; see CaptureQueries::captureIndex.
    QHash<QString, CaptureIndexEntry> captureIndex() const;
    // Normalizes filePath the same way the captures table stores it, so callers
    // holding a captureIndex() can look up their on-disk paths.
    static QString storedPathKey(const QString& filePath);
    bool hasCapturesForGame(int gameId) const;
    // Inserts if new; resolves/creates the game row. Returns new id or -1.
    int insertCapture(const QString& filePath, const QString& type,
                      const QString& gameName, const QString& createdAt,
                      const QString& source, const QString& executablePath = QString());
    bool setFavorite(int captureId, bool favorite);
    bool setThumbnail(int captureId, const QString& thumbnailPath);
    QString thumbnailForCapture(const QString& filePath) const;
    bool setThumbnailForCapture(const QString& filePath, const QString& thumbnailPath);
    bool deleteCapture(int captureId);   // removes the DB row (file handled by caller)

    // Games (only those that have captures), alphabetical.
    QVector<GameEntry> listGames() const;
    bool rememberGameExecutable(const QString& displayName, const QString& executablePath);

    // Input bindings (docs/controller-input.md). Editing UI is 1.0 scope;
    // for now the defaults are seeded once and read back by InputEngine.
    bool seedDefaultBindings();          // inserts defaults only if table empty
    QVector<BindingRow> listBindings() const;

    // Binding overrides (schema v2). Defaults stay in code; these rows are the
    // only user-facing changes, keyed by (device group, device profile, action, slot).
    QVector<BindingOverrideRow> listBindingOverrides() const;
    bool upsertBindingOverride(const BindingOverrideRow& row);
    bool upsertBindingOverridesAtomically(const QVector<BindingOverrideRow>& rows);
    bool clearBindingOverride(const QString& deviceGroup, const QString& deviceProfile,
                               const QString& actionId, int slot);
    bool clearBindingOverridesForGroup(const QString& deviceGroup);
    bool clearBindingOverridesForProfile(const QString& deviceGroup, const QString& deviceProfile);
    bool clearAllBindingOverrides();
    ControllerLayoutRow controllerLayout(const QString& logicalId) const;
    bool upsertControllerLayout(const ControllerLayoutRow& row);
    bool confirmControllerLayout(const QString& logicalId);

    // Mapping presets (schema v8, docs/mapping-presets.md). Content rows use the
    // binding shape; names are unique per group (trimmed, case-insensitive) so
    // assignment pickers stay unambiguous. Every write below is transactional:
    // metadata, content and references either all change or none do. These
    // calls never resolve a preset for a device or game — the input layer owns
    // that; storage must not know which target kind "wins".
    static QString mappingPresetNameKey(const QString& name);
    // The one canonical validator for a legacy `binding_overrides` row: the
    // same parse boundary BindingResolver::reload() has always applied, so the
    // v9 migration and the runtime can never skip rows differently.
    static bool isValidBindingOverrideRow(const BindingOverrideRow& row,
                                          QString* error = nullptr);
    // Rows are validated with the runtime binding grammar (BindingPattern /
    // GestureSpec), never with a storage-local approximation, so a stored row
    // can never be one the binding layer would call malformed. Shared with the
    // migration bridge's composition helpers.
    static bool isValidMappingPresetRow(const QString& deviceGroup, const MappingPresetRow& row);
    // Deterministic, collision-safe migration name: `base`, then `base (2)`,
    // `base (3)`, ... A pre-existing user preset is never renamed or reused -
    // shared by the v9 migration and the runtime materializer so generated
    // names cannot drift apart.
    QString uniqueMigrationPresetName(const QString& deviceGroup, const QString& base) const;
    QVector<MappingPreset> listMappingPresets(const QString& deviceGroup = QString()) const;
    MappingPreset mappingPreset(const QString& presetId) const;
    // Creates metadata + initial rows in one transaction. Returns the new opaque
    // id, or empty on validation failure (unknown group, empty/duplicate name,
    // invalid row) — in that case nothing is written.
    QString createMappingPreset(const QString& deviceGroup, const QString& name,
                                const QVector<MappingPresetRow>& rows = {},
                                const QString& origin = QStringLiteral("user"));
    // Creates an inactive migration preset, its rows and its unverified source
    // link in ONE transaction (cpo-p03 review, correction B): a write failure
    // or a crash can never leave an orphan preset that the next retry would
    // duplicate. Proof and promotion are deliberately not part of this call.
    // Returns the new preset id, or empty with nothing written.
    QString createUnverifiedMigrationSource(const QString& deviceGroup, const QString& name,
                                            const QVector<MappingPresetRow>& rows,
                                            const QString& sourceKey);
    bool renameMappingPreset(const QString& presetId, const QString& name);
    // Replaces the preset's whole sparse row set in one transaction.
    bool replaceMappingPresetRows(const QString& presetId, const QVector<MappingPresetRow>& rows);
    QVector<MappingPresetRow> mappingPresetRows(const QString& presetId) const;
    // Live assignments + migration sources still pointing at this preset.
    int mappingPresetReferenceCount(const QString& presetId) const;
    // Refuses (false, writes nothing) while any reference remains.
    bool deleteMappingPreset(const QString& presetId);
    // Deletes and moves every assignment of the same group onto `keepPresetId`
    // in one transaction; a migration source reference still refuses the delete.
    bool deleteMappingPresetAndReassign(const QString& presetId, const QString& keepPresetId);

    // ---------------------------------------------------------------- cpo-p06
    // The "Built-in defaults" artifact: one reusable, reserved, permanently
    // empty preset per device group. It is the explicit empty winner that masks
    // every compatibility layer below it, which is why it may not be a name:
    // the identity is the reserved id, and the label the user reads is
    // localized app text (reviewer correction Q2). It never appears in the
    // normal library and normal CRUD cannot rename, delete or fill it.
    static QString builtinMappingPresetId(const QString& deviceGroup);
    static bool isBuiltinMappingPresetId(const QString& presetId);
    // Names a user may never store: the reserved display sentinel lives in one
    // control-character namespace, so a translated or pasted label can never
    // become the marker.
    static bool isReservedMappingPresetName(const QString& name);
    // Get-or-create the reserved artifact in ONE transaction. Returns the
    // reserved id, or empty with nothing written.
    QString ensureBuiltinMappingPreset(const QString& deviceGroup);
    // Creates metadata + rows + the target assignment in ONE transaction
    // (cpo-p06 atomic boundaries: duplicate-for-this-controller and
    // adopt-effective-table-and-edit). Returns the new preset id, or empty with
    // nothing written.
    QString createMappingPresetAssigned(const QString& deviceGroup, const QString& name,
                                        const QVector<MappingPresetRow>& rows,
                                        const QString& targetKind, const QString& targetKey,
                                        int gameRowId = -1);
    // Ensures the reserved Built-in preset and points this target at it in ONE
    // transaction. Returns the reserved id, or empty with nothing written.
    QString assignMappingTargetToBuiltin(const QString& deviceGroup, const QString& targetKind,
                                         const QString& targetKey, int gameRowId = -1);
    // `xinput.slotN` / `winmm.slotN`: slot fingerprints from before stable
    // identity existed. They stay explicitly slot-scoped (section 6), and this
    // is the one rule a writer may use to call a key persistably slot-scoped.
    static bool isLegacySlotProfileKey(const QString& key);

    QVector<MappingAssignment> listMappingAssignments(const QString& deviceGroup = QString()) const;
    MappingAssignment mappingAssignment(const QString& deviceGroup, const QString& targetKind,
                                        const QString& targetKey) const;
    // Upserts one typed target. Rejects an unknown kind, a bad key/kind pairing
    // (group_default takes an empty key, every other kind a non-empty one,
    // controller/legacy_slot only in the controller group) and a preset from a
    // different device group. `gameRowId` is kept only for `game` targets.
    // `game` keys are stored in the canonical executable form
    // (GameIdentity::executableKey) whatever spelling is passed, so no two
    // canonically equivalent game rows can exist; `mappingAssignment` and
    // `clearMappingAssignment` normalize the same way.
    bool setMappingAssignment(const QString& deviceGroup, const QString& targetKind,
                              const QString& targetKey, const QString& presetId,
                              int gameRowId = -1);
    bool clearMappingAssignment(const QString& deviceGroup, const QString& targetKind,
                                const QString& targetKey);

    QVector<MappingPresetSource> listMappingPresetSources(const QString& deviceGroup = QString()) const;
    MappingPresetSource mappingPresetSource(const QString& deviceGroup, const QString& sourceKey) const;
    // Records (or relinks) a converted-but-unproven source key with status
    // "unverified" or "retired". This never writes an assignment and never
    // writes `promoted` (a stored promoted row is refused outright): promotion
    // is runtime proof, not storage bookkeeping.
    bool upsertMappingPresetSource(const MappingPresetSource& source);
    // Lifecycle change for an unproven source: only "unverified" and "retired"
    // are accepted. `promoted` is reserved for the atomic path below, and a
    // promoted row is terminal here.
    bool setMappingPresetSourceStatus(const QString& deviceGroup, const QString& sourceKey,
                                      const QString& status);
    // Runtime promotion (docs/mapping-presets.md section 6): writes the durable
    // `controller` assignment for `controllerKey` and marks the source
    // `promoted` in ONE transaction — either both land or neither does. The
    // identity/equality proof belongs to the caller (cpo-p03); storage executes
    // the already-authorized transition and refuses everything else.
    bool promoteMappingPresetSource(const QString& deviceGroup, const QString& sourceKey,
                                    const QString& controllerKey);

    // Watched folders.
    QStringList watchedFolders() const;
    bool addWatchedFolder(const QString& path, const QString& source);
    bool removeWatchedFolder(const QString& path);

private:
    bool migrate();
    bool applyV1();
    bool applyV2();
    bool applyV3();
    bool applyV4();
    bool applyV5();
    bool applyV6();
    bool applyV7();
    bool applyV8();
    // Schema v8 -> v9: convert legacy binding_overrides rows into migration
    // presets/sources (docs/mapping-presets.md section 6). Data-only: no table
    // shape changes, one transaction, `user_version` as the completion marker.
    bool applyV9();
    // Checked read of the legacy rows for v9: a failing SELECT (missing or
    // corrupt binding_overrides) aborts the migration instead of looking like
    // an empty legacy profile (cpo-p03 review, correction C). Backs the public
    // listBindingOverrides() too, so the SELECT and its parsing stay in one
    // place.
    bool loadLegacyOverridesChecked(QVector<BindingOverrideRow>* sink, QString* error) const;
    bool ensureGameMetadataColumns();
    bool repairsV1Done() const;
    bool markRepairsV1Done();
    bool refreshIconsForExtractorFormat();
    int findOrCreateGame(const QString& displayName, const QString& executablePath = QString());
    void updateGameExecutable(int gameId, const QString& executablePath);

    // Mapping-preset internals. The insert helper runs inside the caller's
    // transaction: every public write owns exactly one, so a failure anywhere
    // rolls back metadata, content and references together.
    static bool isMappingDeviceGroup(const QString& deviceGroup);
    static bool isMappingTargetKind(const QString& targetKind);
    bool insertMappingPresetRows(const QString& presetId, const QVector<MappingPresetRow>& rows);
    // One canonical content check for createMappingPreset() and
    // createUnverifiedMigrationSource(): every row storable, no duplicate
    // (action, slot).
    static bool isValidPresetContent(const QString& deviceGroup,
                                     const QVector<MappingPresetRow>& rows);
    // Transaction-aware metadata insert shared by createMappingPreset() and the
    // v9 migration, so preset-row writes and name uniqueness have one path.
    // Returns the new opaque id, or empty (nothing written beyond the caller's
    // transaction, which the caller rolls back). `explicitId` is used only by
    // the reserved Built-in artifact (cpo-p06); every user preset gets a
    // generated opaque id.
    QString insertMappingPresetMetadata(const QString& deviceGroup, const QString& name,
                                        const QString& origin,
                                        const QString& explicitId = QString());
    // One canonical target validation for every assignment writer (the public
    // set/clear path and the cpo-p06 atomic create/ensure paths), so a target a
    // new caller accepts can never differ from what setMappingAssignment()
    // would have accepted. `canonicalKey` receives the persisted key (game keys
    // go through GameIdentity::executableKey).
    bool validateMappingAssignmentTarget(const QString& deviceGroup, const QString& targetKind,
                                         const QString& targetKey, QString* canonicalKey,
                                         QString* error) const;
    // `xinput.slotN` / `winmm.slotN` slot fingerprints: the public declaration
    // above is the one rule (cpo-p06 target derivation reuses it).
    // One typed assignment write; the caller owns the transaction.
    bool upsertMappingAssignmentRow(const QString& deviceGroup, const QString& targetKind,
                                    const QString& targetKey, const QString& presetId,
                                    int gameRowId);

    QString m_filePath;
    QSqlDatabase m_db;
};
